/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnchorPoint,
  SeededScoreIncrement,
} from '../models/index';
import {
    AnchorPointFromJSON,
    AnchorPointToJSON,
    SeededScoreIncrementFromJSON,
    SeededScoreIncrementToJSON,
} from '../models/index';

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @interface AnchorPointScoresIncrementRequest
 * @typedef {AnchorPointScoresIncrementRequest}
 */
export interface AnchorPointScoresIncrementRequest {
    /**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @type {string}
 */
anchorPoint: string;
    /**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @type {?SeededScoreIncrement}
 */
seededScoreIncrement?: SeededScoreIncrement;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @interface AnchorPointSpecificAnchorPointSnapshotRequest
 * @typedef {AnchorPointSpecificAnchorPointSnapshotRequest}
 */
export interface AnchorPointSpecificAnchorPointSnapshotRequest {
    /**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @type {string}
 */
anchorPoint: string;
    /**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @type {?boolean}
 */
transferables?: boolean;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @interface AnchorPointUpdateRequest
 * @typedef {AnchorPointUpdateRequest}
 */
export interface AnchorPointUpdateRequest {
    /**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @type {?boolean}
 */
transferables?: boolean;
    /**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @type {?AnchorPoint}
 */
anchorPoint?: AnchorPoint;
}

/**
 *
 */
export class AnchorPointApi extends runtime.BaseAPI {

    /**
     * This will take in a SeededScoreIncrement and will increment the material relative to the incoming body.
     * \'/anchor_point/{anchor_point}/scores/increment\' [POST]
     */
    async anchorPointScoresIncrementRaw(requestParameters: AnchorPointScoresIncrementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.anchorPoint === null || requestParameters.anchorPoint === undefined) {
            throw new runtime.RequiredError('anchorPoint','Required parameter requestParameters.anchorPoint was null or undefined when calling anchorPointScoresIncrement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/anchor_point/{anchor_point}/scores/increment`.replace(`{${"anchor_point"}}`, encodeURIComponent(String(requestParameters.anchorPoint))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SeededScoreIncrementToJSON(requestParameters.seededScoreIncrement),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This will take in a SeededScoreIncrement and will increment the material relative to the incoming body.
     * \'/anchor_point/{anchor_point}/scores/increment\' [POST]
     */
    async anchorPointScoresIncrement(requestParameters: AnchorPointScoresIncrementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.anchorPointScoresIncrementRaw(requestParameters, initOverrides);
    }

    /**
     * This will get a snapshot of a single anchorPoint.
     * /anchor_point/{anchor_point} [GET]
     */
    async anchorPointSpecificAnchorPointSnapshotRaw(requestParameters: AnchorPointSpecificAnchorPointSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnchorPoint>> {
        if (requestParameters.anchorPoint === null || requestParameters.anchorPoint === undefined) {
            throw new runtime.RequiredError('anchorPoint','Required parameter requestParameters.anchorPoint was null or undefined when calling anchorPointSpecificAnchorPointSnapshot.');
        }

        const queryParameters: any = {};

        if (requestParameters.transferables !== undefined) {
            queryParameters['transferables'] = requestParameters.transferables;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/anchor_point/{anchor_point}`.replace(`{${"anchor_point"}}`, encodeURIComponent(String(requestParameters.anchorPoint))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnchorPointFromJSON(jsonValue));
    }

    /**
     * This will get a snapshot of a single anchorPoint.
     * /anchor_point/{anchor_point} [GET]
     */
    async anchorPointSpecificAnchorPointSnapshot(requestParameters: AnchorPointSpecificAnchorPointSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnchorPoint> {
        const response = await this.anchorPointSpecificAnchorPointSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This will update a specific anchorPoint.
     * /anchor_point/update [POST]
     */
    async anchorPointUpdateRaw(requestParameters: AnchorPointUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnchorPoint>> {
        const queryParameters: any = {};

        if (requestParameters.transferables !== undefined) {
            queryParameters['transferables'] = requestParameters.transferables;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/anchor_point/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AnchorPointToJSON(requestParameters.anchorPoint),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnchorPointFromJSON(jsonValue));
    }

    /**
     * This will update a specific anchorPoint.
     * /anchor_point/update [POST]
     */
    async anchorPointUpdate(requestParameters: AnchorPointUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnchorPoint> {
        const response = await this.anchorPointUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
