/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AllocationStatusEnum } from './AllocationStatusEnum';
import {
    AllocationStatusEnumFromJSON,
    AllocationStatusEnumFromJSONTyped,
    AllocationStatusEnumToJSON,
} from './AllocationStatusEnum';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 * This is one of the 3 possible urls that will route to your cloud :).
 * @export
 * @interface AllocationCloudUrl
 */
export interface AllocationCloudUrl {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof AllocationCloudUrl
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {AllocationStatusEnum}
     * @memberof AllocationCloudUrl
     */
    status: AllocationStatusEnum;
    /**
     * this is the base url that is used to communicat with your vpc.
     * @type {string}
     * @memberof AllocationCloudUrl
     */
    url: string;
}

/**
 * Check if a given object implements the AllocationCloudUrl interface.
 */
export function instanceOfAllocationCloudUrl(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {*} json
 * @returns {AllocationCloudUrl}
 */
export function AllocationCloudUrlFromJSON(json: any): AllocationCloudUrl {
    return AllocationCloudUrlFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {AllocationCloudUrl}
 */
export function AllocationCloudUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocationCloudUrl {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'status': AllocationStatusEnumFromJSON(json['status']),
        'url': json['url'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {?(AllocationCloudUrl | null)} [value]
 * @returns {*}
 */
export function AllocationCloudUrlToJSON(value?: AllocationCloudUrl | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'status': AllocationStatusEnumToJSON(value.status),
        'url': value.url,
    };
}

