/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is used to describe a specific type of annotation. NOTE** This is linked to the annotation_type_filter in the parameters folder(if you change an enum here, please adjust the enum there.)
 * @export
 */
export const AnnotationTypeEnum = {
    Description: 'DESCRIPTION',
    Comment: 'COMMENT',
    Documentation: 'DOCUMENTATION',
    Summary: 'SUMMARY',
    Explanation: 'EXPLANATION',
    GitCommit: 'GIT_COMMIT'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @typedef {AnnotationTypeEnum}
 */
export type AnnotationTypeEnum = typeof AnnotationTypeEnum[keyof typeof AnnotationTypeEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {*} json
 * @returns {AnnotationTypeEnum}
 */
export function AnnotationTypeEnumFromJSON(json: any): AnnotationTypeEnum {
    return AnnotationTypeEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {AnnotationTypeEnum}
 */
export function AnnotationTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotationTypeEnum {
    return json as AnnotationTypeEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {?(AnnotationTypeEnum | null)} [value]
 * @returns {*}
 */
export function AnnotationTypeEnumToJSON(value?: AnnotationTypeEnum | null): any {
    return value as any;
}

