/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnnotationTypeEnum } from './AnnotationTypeEnum';
import {
    AnnotationTypeEnumFromJSON,
    AnnotationTypeEnumFromJSONTyped,
    AnnotationTypeEnumToJSON,
} from './AnnotationTypeEnum';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 *
 * @export
 * @interface AssetFilterPhraseOptions
 */
export interface AssetFilterPhraseOptions {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof AssetFilterPhraseOptions
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {AnnotationTypeEnum}
     * @memberof AssetFilterPhraseOptions
     */
    annotation?: AnnotationTypeEnum;
}

/**
 * Check if a given object implements the AssetFilterPhraseOptions interface.
 */
export function instanceOfAssetFilterPhraseOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {*} json
 * @returns {AssetFilterPhraseOptions}
 */
export function AssetFilterPhraseOptionsFromJSON(json: any): AssetFilterPhraseOptions {
    return AssetFilterPhraseOptionsFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {AssetFilterPhraseOptions}
 */
export function AssetFilterPhraseOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetFilterPhraseOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'annotation': !exists(json, 'annotation') ? undefined : AnnotationTypeEnumFromJSON(json['annotation']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {?(AssetFilterPhraseOptions | null)} [value]
 * @returns {*}
 */
export function AssetFilterPhraseOptionsToJSON(value?: AssetFilterPhraseOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'annotation': AnnotationTypeEnumToJSON(value.annotation),
    };
}

