/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum used for the status of creating a backup or restoring a backup.
 * @export
 */
export const BackupStatusEnum = {
    Initialized: 'INITIALIZED',
    InProgress: 'IN-PROGRESS',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Unknown: 'UNKNOWN',
    Canceled: 'CANCELED',
    Reset: 'RESET'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @typedef {BackupStatusEnum}
 */
export type BackupStatusEnum = typeof BackupStatusEnum[keyof typeof BackupStatusEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @returns {BackupStatusEnum}
 */
export function BackupStatusEnumFromJSON(json: any): BackupStatusEnum {
    return BackupStatusEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {BackupStatusEnum}
 */
export function BackupStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupStatusEnum {
    return json as BackupStatusEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {?(BackupStatusEnum | null)} [value]
 * @returns {*}
 */
export function BackupStatusEnumToJSON(value?: BackupStatusEnum | null): any {
    return value as any;
}

