/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifically supported renderings...usually between generic types
 * @export
 */
export const ClassificationRenderingEnum = {
    Html: 'HTML',
    TwentyFourBitAnsiEscapedSequences: 'TWENTY_FOUR_BIT_ANSI_ESCAPED_SEQUENCES',
    HighlightJsHtml: 'HIGHLIGHT_JS_HTML'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @typedef {ClassificationRenderingEnum}
 */
export type ClassificationRenderingEnum = typeof ClassificationRenderingEnum[keyof typeof ClassificationRenderingEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {*} json
 * @returns {ClassificationRenderingEnum}
 */
export function ClassificationRenderingEnumFromJSON(json: any): ClassificationRenderingEnum {
    return ClassificationRenderingEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {ClassificationRenderingEnum}
 */
export function ClassificationRenderingEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationRenderingEnum {
    return json as ClassificationRenderingEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {?(ClassificationRenderingEnum | null)} [value]
 * @returns {*}
 */
export function ClassificationRenderingEnumToJSON(value?: ClassificationRenderingEnum | null): any {
    return value as any;
}

