/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * EXTERNAL_RESOURCE_REFERENCE can be thought of as anything such as URL, URI, UNIX PATH, etc
 * @export
 */
export const ClassificationGenericEnum = {
    Code: 'CODE',
    Text: 'TEXT',
    Image: 'IMAGE',
    Video: 'VIDEO',
    ExternalResourceReference: 'EXTERNAL_RESOURCE_REFERENCE',
    Unknown: 'UNKNOWN',
    File: 'FILE'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @typedef {ClassificationGenericEnum}
 */
export type ClassificationGenericEnum = typeof ClassificationGenericEnum[keyof typeof ClassificationGenericEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @returns {ClassificationGenericEnum}
 */
export function ClassificationGenericEnumFromJSON(json: any): ClassificationGenericEnum {
    return ClassificationGenericEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {ClassificationGenericEnum}
 */
export function ClassificationGenericEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationGenericEnum {
    return json as ClassificationGenericEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {?(ClassificationGenericEnum | null)} [value]
 * @returns {*}
 */
export function ClassificationGenericEnumToJSON(value?: ClassificationGenericEnum | null): any {
    return value as any;
}

