/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CodeAnalysis } from './CodeAnalysis';
import {
    CodeAnalysisFromJSON,
    CodeAnalysisFromJSONTyped,
    CodeAnalysisToJSON,
} from './CodeAnalysis';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 *
 * @export
 * @interface CodeAnalyses
 */
export interface CodeAnalyses {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof CodeAnalyses
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {Array<CodeAnalysis>}
     * @memberof CodeAnalyses
     */
    iterable: Array<CodeAnalysis>;
}

/**
 * Check if a given object implements the CodeAnalyses interface.
 */
export function instanceOfCodeAnalyses(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iterable" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {*} json
 * @returns {CodeAnalyses}
 */
export function CodeAnalysesFromJSON(json: any): CodeAnalyses {
    return CodeAnalysesFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {CodeAnalyses}
 */
export function CodeAnalysesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeAnalyses {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(CodeAnalysisFromJSON)),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {?(CodeAnalyses | null)} [value]
 * @returns {*}
 */
export function CodeAnalysesToJSON(value?: CodeAnalyses | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'iterable': ((value.iterable as Array<any>).map(CodeAnalysisToJSON)),
    };
}

