/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 * This is a detected External Application that comes from our endpoint that will get a snapshot of the installed applications on your machine.
 * @export
 * @interface DetectedExternalApplication
 */
export interface DetectedExternalApplication {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof DetectedExternalApplication
     */
    schema?: EmbeddedModelSchema;
    /**
     * this is the name of the application
     * @type {string}
     * @memberof DetectedExternalApplication
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof DetectedExternalApplication
     */
    version?: string;
}

/**
 * Check if a given object implements the DetectedExternalApplication interface.
 */
export function instanceOfDetectedExternalApplication(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {*} json
 * @returns {DetectedExternalApplication}
 */
export function DetectedExternalApplicationFromJSON(json: any): DetectedExternalApplication {
    return DetectedExternalApplicationFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {DetectedExternalApplication}
 */
export function DetectedExternalApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectedExternalApplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'name': json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:11 AM
 *
 * @export
 * @param {?(DetectedExternalApplication | null)} [value]
 * @returns {*}
 */
export function DetectedExternalApplicationToJSON(value?: DetectedExternalApplication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'name': value.name,
        'version': value.version,
    };
}

