/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiscoveredRelatedTag } from './DiscoveredRelatedTag';
import {
    DiscoveredRelatedTagFromJSON,
    DiscoveredRelatedTagFromJSONTyped,
    DiscoveredRelatedTagToJSON,
} from './DiscoveredRelatedTag';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 *
 * @export
 * @interface DiscoveredRelatedTags
 */
export interface DiscoveredRelatedTags {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof DiscoveredRelatedTags
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof DiscoveredRelatedTags
     */
    application: string;
    /**
     *
     * @type {Array<DiscoveredRelatedTag>}
     * @memberof DiscoveredRelatedTags
     */
    iterable: Array<DiscoveredRelatedTag>;
}

/**
 * Check if a given object implements the DiscoveredRelatedTags interface.
 */
export function instanceOfDiscoveredRelatedTags(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "application" in value;
    isInstance = isInstance && "iterable" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {*} json
 * @returns {DiscoveredRelatedTags}
 */
export function DiscoveredRelatedTagsFromJSON(json: any): DiscoveredRelatedTags {
    return DiscoveredRelatedTagsFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {DiscoveredRelatedTags}
 */
export function DiscoveredRelatedTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveredRelatedTags {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'application': json['application'],
        'iterable': ((json['iterable'] as Array<any>).map(DiscoveredRelatedTagFromJSON)),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:13 AM
 *
 * @export
 * @param {?(DiscoveredRelatedTags | null)} [value]
 * @returns {*}
 */
export function DiscoveredRelatedTagsToJSON(value?: DiscoveredRelatedTags | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'application': value.application,
        'iterable': ((value.iterable as Array<any>).map(DiscoveredRelatedTagToJSON)),
    };
}

