/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { SeededTag } from './SeededTag';
import {
    SeededTagFromJSON,
    SeededTagFromJSONTyped,
    SeededTagToJSON,
} from './SeededTag';

/**
 *
 * @export
 * @interface DiscoveredRelatedTag
 */
export interface DiscoveredRelatedTag {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof DiscoveredRelatedTag
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {SeededTag}
     * @memberof DiscoveredRelatedTag
     */
    seed: SeededTag;
}

/**
 * Check if a given object implements the DiscoveredRelatedTag interface.
 */
export function instanceOfDiscoveredRelatedTag(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "seed" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @returns {DiscoveredRelatedTag}
 */
export function DiscoveredRelatedTagFromJSON(json: any): DiscoveredRelatedTag {
    return DiscoveredRelatedTagFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {DiscoveredRelatedTag}
 */
export function DiscoveredRelatedTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveredRelatedTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'seed': SeededTagFromJSON(json['seed']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {?(DiscoveredRelatedTag | null)} [value]
 * @returns {*}
 */
export function DiscoveredRelatedTagToJSON(value?: DiscoveredRelatedTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'seed': SeededTagToJSON(value.seed),
    };
}

