/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiscoveredAssets } from './DiscoveredAssets';
import {
    DiscoveredAssetsFromJSON,
    DiscoveredAssetsFromJSONTyped,
    DiscoveredAssetsToJSON,
} from './DiscoveredAssets';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 * This will return assets that were extracted from the html webpage. This will contain the original url so you can double check the results wtih the results you passed in, but it will remain in the same order that it was passed in if used within the /discover/discover/html/webpage endpoint.
 * @export
 * @interface DiscoveredHtmlWebpage
 */
export interface DiscoveredHtmlWebpage {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof DiscoveredHtmlWebpage
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {DiscoveredAssets}
     * @memberof DiscoveredHtmlWebpage
     */
    assets: DiscoveredAssets;
    /**
     *
     * @type {string}
     * @memberof DiscoveredHtmlWebpage
     */
    url: string;
}

/**
 * Check if a given object implements the DiscoveredHtmlWebpage interface.
 */
export function instanceOfDiscoveredHtmlWebpage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "assets" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @returns {DiscoveredHtmlWebpage}
 */
export function DiscoveredHtmlWebpageFromJSON(json: any): DiscoveredHtmlWebpage {
    return DiscoveredHtmlWebpageFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {DiscoveredHtmlWebpage}
 */
export function DiscoveredHtmlWebpageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveredHtmlWebpage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'assets': DiscoveredAssetsFromJSON(json['assets']),
        'url': json['url'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:12 AM
 *
 * @export
 * @param {?(DiscoveredHtmlWebpage | null)} [value]
 * @returns {*}
 */
export function DiscoveredHtmlWebpageToJSON(value?: DiscoveredHtmlWebpage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'assets': DiscoveredAssetsToJSON(value.assets),
        'url': value.url,
    };
}

