/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
} from './Node';

/**
 *
 * @export
 * @interface Edges
 */
export interface Edges {
    /**
     *
     * @type {Array<Node>}
     * @memberof Edges
     */
    iterable: Array<Node>;
}

/**
 * Check if a given object implements the Edges interface.
 */
export function instanceOfEdges(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iterable" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {*} json
 * @returns {Edges}
 */
export function EdgesFromJSON(json: any): Edges {
    return EdgesFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {Edges}
 */
export function EdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Edges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'iterable': ((json['iterable'] as Array<any>).map(NodeFromJSON)),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {?(Edges | null)} [value]
 * @returns {*}
 */
export function EdgesToJSON(value?: Edges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'iterable': ((value.iterable as Array<any>).map(NodeToJSON)),
    };
}

