/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { FlattenedShare } from './FlattenedShare';
import {
    FlattenedShareFromJSON,
    FlattenedShareFromJSONTyped,
    FlattenedShareToJSON,
} from './FlattenedShare';
import type { Score } from './Score';
import {
    ScoreFromJSON,
    ScoreFromJSONTyped,
    ScoreToJSON,
} from './Score';

/**
 * This is just an iterable of our individual share models.
 * @export
 * @interface FlattenedShares
 */
export interface FlattenedShares {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof FlattenedShares
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {Array<FlattenedShare>}
     * @memberof FlattenedShares
     */
    iterable: Array<FlattenedShare>;
    /**
     *
     * @type {Score}
     * @memberof FlattenedShares
     */
    score?: Score;
}

/**
 * Check if a given object implements the FlattenedShares interface.
 */
export function instanceOfFlattenedShares(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iterable" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:18 AM
 *
 * @export
 * @param {*} json
 * @returns {FlattenedShares}
 */
export function FlattenedSharesFromJSON(json: any): FlattenedShares {
    return FlattenedSharesFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:18 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {FlattenedShares}
 */
export function FlattenedSharesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlattenedShares {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(FlattenedShareFromJSON)),
        'score': !exists(json, 'score') ? undefined : ScoreFromJSON(json['score']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:18 AM
 *
 * @export
 * @param {?(FlattenedShares | null)} [value]
 * @returns {*}
 */
export function FlattenedSharesToJSON(value?: FlattenedShares | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'iterable': ((value.iterable as Array<any>).map(FlattenedShareToJSON)),
        'score': ScoreToJSON(value.score),
    };
}

