/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { ReferencedConversation } from './ReferencedConversation';
import {
    ReferencedConversationFromJSON,
    ReferencedConversationFromJSONTyped,
    ReferencedConversationToJSON,
} from './ReferencedConversation';
import type { Score } from './Score';
import {
    ScoreFromJSON,
    ScoreFromJSONTyped,
    ScoreToJSON,
} from './Score';

/**
 * Flattened version of conversations.
 * @export
 * @interface FlattenedConversations
 */
export interface FlattenedConversations {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof FlattenedConversations
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {Array<ReferencedConversation>}
     * @memberof FlattenedConversations
     */
    iterable: Array<ReferencedConversation>;
    /**
     * This is a Map<String, int> where the the key is an Conversation id.
     * @type {{ [key: string]: number; }}
     * @memberof FlattenedConversations
     */
    indices?: { [key: string]: number; };
    /**
     *
     * @type {Score}
     * @memberof FlattenedConversations
     */
    score?: Score;
}

/**
 * Check if a given object implements the FlattenedConversations interface.
 */
export function instanceOfFlattenedConversations(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iterable" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {*} json
 * @returns {FlattenedConversations}
 */
export function FlattenedConversationsFromJSON(json: any): FlattenedConversations {
    return FlattenedConversationsFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {FlattenedConversations}
 */
export function FlattenedConversationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlattenedConversations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(ReferencedConversationFromJSON)),
        'indices': !exists(json, 'indices') ? undefined : json['indices'],
        'score': !exists(json, 'score') ? undefined : ScoreFromJSON(json['score']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:14 AM
 *
 * @export
 * @param {?(FlattenedConversations | null)} [value]
 * @returns {*}
 */
export function FlattenedConversationsToJSON(value?: FlattenedConversations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'iterable': ((value.iterable as Array<any>).map(ReferencedConversationToJSON)),
        'indices': value.indices,
        'score': ScoreToJSON(value.score),
    };
}

