/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 * This will describe the font that the user sees.
 * @export
 * @interface Font
 */
export interface Font {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof Font
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {number}
     * @memberof Font
     */
    size: number;
}

/**
 * Check if a given object implements the Font interface.
 */
export function instanceOfFont(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "size" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:17 AM
 *
 * @export
 * @param {*} json
 * @returns {Font}
 */
export function FontFromJSON(json: any): Font {
    return FontFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:17 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {Font}
 */
export function FontFromJSONTyped(json: any, ignoreDiscriminator: boolean): Font {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'size': json['size'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:17 AM
 *
 * @export
 * @param {?(Font | null)} [value]
 * @returns {*}
 */
export function FontToJSON(value?: Font | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'size': value.size,
    };
}

