/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { GitHubGistDistribution } from './GitHubGistDistribution';
import {
    GitHubGistDistributionFromJSON,
    GitHubGistDistributionFromJSONTyped,
    GitHubGistDistributionToJSON,
} from './GitHubGistDistribution';

/**
 *
 * @export
 * @interface GitHubDistribution
 */
export interface GitHubDistribution {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof GitHubDistribution
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {GitHubGistDistribution}
     * @memberof GitHubDistribution
     */
    gist?: GitHubGistDistribution;
}

/**
 * Check if a given object implements the GitHubDistribution interface.
 */
export function instanceOfGitHubDistribution(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:17 AM
 *
 * @export
 * @param {*} json
 * @returns {GitHubDistribution}
 */
export function GitHubDistributionFromJSON(json: any): GitHubDistribution {
    return GitHubDistributionFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:17 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {GitHubDistribution}
 */
export function GitHubDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitHubDistribution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'gist': !exists(json, 'gist') ? undefined : GitHubGistDistributionFromJSON(json['gist']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:17 AM
 *
 * @export
 * @param {?(GitHubDistribution | null)} [value]
 * @returns {*}
 */
export function GitHubDistributionToJSON(value?: GitHubDistribution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'gist': GitHubGistDistributionToJSON(value.gist),
    };
}

