/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { GraphicalImageStatistics } from './GraphicalImageStatistics';
import {
    GraphicalImageStatisticsFromJSON,
    GraphicalImageStatisticsFromJSONTyped,
    GraphicalImageStatisticsToJSON,
} from './GraphicalImageStatistics';

/**
 *
 * @export
 * @interface GraphicalImageProcessing
 */
export interface GraphicalImageProcessing {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof GraphicalImageProcessing
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {GraphicalImageStatistics}
     * @memberof GraphicalImageProcessing
     */
    statistics?: GraphicalImageStatistics;
}

/**
 * Check if a given object implements the GraphicalImageProcessing interface.
 */
export function instanceOfGraphicalImageProcessing(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @returns {GraphicalImageProcessing}
 */
export function GraphicalImageProcessingFromJSON(json: any): GraphicalImageProcessing {
    return GraphicalImageProcessingFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {GraphicalImageProcessing}
 */
export function GraphicalImageProcessingFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphicalImageProcessing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'statistics': !exists(json, 'statistics') ? undefined : GraphicalImageStatisticsFromJSON(json['statistics']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {?(GraphicalImageProcessing | null)} [value]
 * @returns {*}
 */
export function GraphicalImageProcessingToJSON(value?: GraphicalImageProcessing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'statistics': GraphicalImageStatisticsToJSON(value.statistics),
    };
}

