/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GraphicalOCRDescriptiveStatisticsConfidence
 */
export interface GraphicalOCRDescriptiveStatisticsConfidence {
    /**
     *
     * @type {string}
     * @memberof GraphicalOCRDescriptiveStatisticsConfidence
     */
    mean: string;
}

/**
 * Check if a given object implements the GraphicalOCRDescriptiveStatisticsConfidence interface.
 */
export function instanceOfGraphicalOCRDescriptiveStatisticsConfidence(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mean" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @returns {GraphicalOCRDescriptiveStatisticsConfidence}
 */
export function GraphicalOCRDescriptiveStatisticsConfidenceFromJSON(json: any): GraphicalOCRDescriptiveStatisticsConfidence {
    return GraphicalOCRDescriptiveStatisticsConfidenceFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {GraphicalOCRDescriptiveStatisticsConfidence}
 */
export function GraphicalOCRDescriptiveStatisticsConfidenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphicalOCRDescriptiveStatisticsConfidence {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'mean': json['mean'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {?(GraphicalOCRDescriptiveStatisticsConfidence | null)} [value]
 * @returns {*}
 */
export function GraphicalOCRDescriptiveStatisticsConfidenceToJSON(value?: GraphicalOCRDescriptiveStatisticsConfidence | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'mean': value.mean,
    };
}

