/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { GraphicalOCRDescriptiveStatisticsConfidence } from './GraphicalOCRDescriptiveStatisticsConfidence';
import {
    GraphicalOCRDescriptiveStatisticsConfidenceFromJSON,
    GraphicalOCRDescriptiveStatisticsConfidenceFromJSONTyped,
    GraphicalOCRDescriptiveStatisticsConfidenceToJSON,
} from './GraphicalOCRDescriptiveStatisticsConfidence';

/**
 * Model for monitoring and evaluating the OCR feature
 * @export
 * @interface GraphicalOCRDescriptiveStatistics
 */
export interface GraphicalOCRDescriptiveStatistics {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    asset: string;
    /**
     *
     * @type {string}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    user: string;
    /**
     *
     * @type {string}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    model: string;
    /**
     *
     * @type {string}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    created: string;
    /**
     *
     * @type {string}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    os: string;
    /**
     *
     * @type {GraphicalOCRDescriptiveStatisticsConfidence}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    confidence: GraphicalOCRDescriptiveStatisticsConfidence;
    /**
     *
     * @type {string}
     * @memberof GraphicalOCRDescriptiveStatistics
     */
    duration: string;
}

/**
 * Check if a given object implements the GraphicalOCRDescriptiveStatistics interface.
 */
export function instanceOfGraphicalOCRDescriptiveStatistics(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "asset" in value;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "model" in value;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "os" in value;
    isInstance = isInstance && "confidence" in value;
    isInstance = isInstance && "duration" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @returns {GraphicalOCRDescriptiveStatistics}
 */
export function GraphicalOCRDescriptiveStatisticsFromJSON(json: any): GraphicalOCRDescriptiveStatistics {
    return GraphicalOCRDescriptiveStatisticsFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {GraphicalOCRDescriptiveStatistics}
 */
export function GraphicalOCRDescriptiveStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphicalOCRDescriptiveStatistics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'asset': json['asset'],
        'user': json['user'],
        'model': json['model'],
        'created': json['created'],
        'os': json['os'],
        'confidence': GraphicalOCRDescriptiveStatisticsConfidenceFromJSON(json['confidence']),
        'duration': json['duration'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {?(GraphicalOCRDescriptiveStatistics | null)} [value]
 * @returns {*}
 */
export function GraphicalOCRDescriptiveStatisticsToJSON(value?: GraphicalOCRDescriptiveStatistics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'asset': value.asset,
        'user': value.user,
        'model': value.model,
        'created': value.created,
        'os': value.os,
        'confidence': GraphicalOCRDescriptiveStatisticsConfidenceToJSON(value.confidence),
        'duration': value.duration,
    };
}

