/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { OSHealth } from './OSHealth';
import {
    OSHealthFromJSON,
    OSHealthFromJSONTyped,
    OSHealthToJSON,
} from './OSHealth';

/**
 * This is a health model used to determine the "health" of the os server and cloud server(Coming Soon). READONLY Model.
 * @export
 * @interface Health
 */
export interface Health {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof Health
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {OSHealth}
     * @memberof Health
     */
    os: OSHealth;
}

/**
 * Check if a given object implements the Health interface.
 */
export function instanceOfHealth(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "os" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @returns {Health}
 */
export function HealthFromJSON(json: any): Health {
    return HealthFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {Health}
 */
export function HealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): Health {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'os': OSHealthFromJSON(json['os']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:16 AM
 *
 * @export
 * @param {?(Health | null)} [value]
 * @returns {*}
 */
export function HealthToJSON(value?: Health | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'os': OSHealthToJSON(value.os),
    };
}

