/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum used for the status of the progress in downloading a model.
 * @export
 */
export const ModelDownloadProgressStatusEnum = {
    Initialized: 'INITIALIZED',
    InProgress: 'IN-PROGRESS',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Unknown: 'UNKNOWN',
    Canceled: 'CANCELED',
    Reset: 'RESET'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:34 AM
 *
 * @export
 * @typedef {ModelDownloadProgressStatusEnum}
 */
export type ModelDownloadProgressStatusEnum = typeof ModelDownloadProgressStatusEnum[keyof typeof ModelDownloadProgressStatusEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:34 AM
 *
 * @export
 * @param {*} json
 * @returns {ModelDownloadProgressStatusEnum}
 */
export function ModelDownloadProgressStatusEnumFromJSON(json: any): ModelDownloadProgressStatusEnum {
    return ModelDownloadProgressStatusEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:34 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {ModelDownloadProgressStatusEnum}
 */
export function ModelDownloadProgressStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDownloadProgressStatusEnum {
    return json as ModelDownloadProgressStatusEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:34 AM
 *
 * @export
 * @param {?(ModelDownloadProgressStatusEnum | null)} [value]
 * @returns {*}
 */
export function ModelDownloadProgressStatusEnumToJSON(value?: ModelDownloadProgressStatusEnum | null): any {
    return value as any;
}

