/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This describes the type of a node ie an asset, tag, website, format... ETC
 * @export
 */
export const NodeTypeEnum = {
    Tag: 'TAG',
    Website: 'WEBSITE',
    Format: 'FORMAT',
    Asset: 'ASSET'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @typedef {NodeTypeEnum}
 */
export type NodeTypeEnum = typeof NodeTypeEnum[keyof typeof NodeTypeEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @returns {NodeTypeEnum}
 */
export function NodeTypeEnumFromJSON(json: any): NodeTypeEnum {
    return NodeTypeEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {NodeTypeEnum}
 */
export function NodeTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeTypeEnum {
    return json as NodeTypeEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {?(NodeTypeEnum | null)} [value]
 * @returns {*}
 */
export function NodeTypeEnumToJSON(value?: NodeTypeEnum | null): any {
    return value as any;
}

