/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A Model to support account creation to Auth0's Database.
 * @export
 * @interface OAuthAccount
 */
export interface OAuthAccount {
    /**
     * The client_id of your client.
     * @type {string}
     * @memberof OAuthAccount
     */
    clientId: string;
    /**
     * The user's email address.
     * @type {string}
     * @memberof OAuthAccount
     */
    email: string;
    /**
     * The name of the database configured to your client.
     * @type {string}
     * @memberof OAuthAccount
     */
    connection: string;
    /**
     * The user's username. Only valid if the connection requires a username.
     * @type {string}
     * @memberof OAuthAccount
     */
    username: string;
    /**
     * The user's given name(s).
     * @type {string}
     * @memberof OAuthAccount
     */
    givenName: string;
    /**
     * The user's family name(s).
     * @type {string}
     * @memberof OAuthAccount
     */
    familyName: string;
    /**
     * The user's full name.
     * @type {string}
     * @memberof OAuthAccount
     */
    name: string;
    /**
     * A URI pointing to the user's picture.
     * @type {string}
     * @memberof OAuthAccount
     */
    picture: string;
    /**
     * The user's nickname.
     * @type {string}
     * @memberof OAuthAccount
     */
    nickname: string;
}

/**
 * Check if a given object implements the OAuthAccount interface.
 */
export function instanceOfOAuthAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "connection" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "givenName" in value;
    isInstance = isInstance && "familyName" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "picture" in value;
    isInstance = isInstance && "nickname" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @returns {OAuthAccount}
 */
export function OAuthAccountFromJSON(json: any): OAuthAccount {
    return OAuthAccountFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {OAuthAccount}
 */
export function OAuthAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'clientId': json['client_id'],
        'email': json['email'],
        'connection': json['connection'],
        'username': json['username'],
        'givenName': json['given_name'],
        'familyName': json['family_name'],
        'name': json['name'],
        'picture': json['picture'],
        'nickname': json['nickname'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {?(OAuthAccount | null)} [value]
 * @returns {*}
 */
export function OAuthAccountToJSON(value?: OAuthAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'client_id': value.clientId,
        'email': value.email,
        'connection': value.connection,
        'username': value.username,
        'given_name': value.givenName,
        'family_name': value.familyName,
        'name': value.name,
        'picture': value.picture,
        'nickname': value.nickname,
    };
}

