/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 * This is the input model for the /open_ai/models/list endpoint.
 * @export
 * @interface OpenAIModelsListInput
 */
export interface OpenAIModelsListInput {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof OpenAIModelsListInput
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof OpenAIModelsListInput
     */
    user: string;
}

/**
 * Check if a given object implements the OpenAIModelsListInput interface.
 */
export function instanceOfOpenAIModelsListInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @returns {OpenAIModelsListInput}
 */
export function OpenAIModelsListInputFromJSON(json: any): OpenAIModelsListInput {
    return OpenAIModelsListInputFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {OpenAIModelsListInput}
 */
export function OpenAIModelsListInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenAIModelsListInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'user': json['user'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {?(OpenAIModelsListInput | null)} [value]
 * @returns {*}
 */
export function OpenAIModelsListInputToJSON(value?: OpenAIModelsListInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'user': value.user,
    };
}

