/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { OSDeviceGPUHardwareCapabilitiesInformation } from './OSDeviceGPUHardwareCapabilitiesInformation';
import {
    OSDeviceGPUHardwareCapabilitiesInformationFromJSON,
    OSDeviceGPUHardwareCapabilitiesInformationFromJSONTyped,
    OSDeviceGPUHardwareCapabilitiesInformationToJSON,
} from './OSDeviceGPUHardwareCapabilitiesInformation';

/**
 * This will let us know specific hardware information related to the GPU.
 * @export
 * @interface OSDeviceGPUHardwareInformation
 */
export interface OSDeviceGPUHardwareInformation {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof OSDeviceGPUHardwareInformation
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof OSDeviceGPUHardwareInformation
     */
    name?: string;
    /**
     *
     * @type {number}
     * @memberof OSDeviceGPUHardwareInformation
     */
    memory?: number;
    /**
     *
     * @type {OSDeviceGPUHardwareCapabilitiesInformation}
     * @memberof OSDeviceGPUHardwareInformation
     */
    capabilities?: OSDeviceGPUHardwareCapabilitiesInformation;
}

/**
 * Check if a given object implements the OSDeviceGPUHardwareInformation interface.
 */
export function instanceOfOSDeviceGPUHardwareInformation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @returns {OSDeviceGPUHardwareInformation}
 */
export function OSDeviceGPUHardwareInformationFromJSON(json: any): OSDeviceGPUHardwareInformation {
    return OSDeviceGPUHardwareInformationFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {OSDeviceGPUHardwareInformation}
 */
export function OSDeviceGPUHardwareInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OSDeviceGPUHardwareInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'memory': !exists(json, 'memory') ? undefined : json['memory'],
        'capabilities': !exists(json, 'capabilities') ? undefined : OSDeviceGPUHardwareCapabilitiesInformationFromJSON(json['capabilities']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:33 AM
 *
 * @export
 * @param {?(OSDeviceGPUHardwareInformation | null)} [value]
 * @returns {*}
 */
export function OSDeviceGPUHardwareInformationToJSON(value?: OSDeviceGPUHardwareInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'name': value.name,
        'memory': value.memory,
        'capabilities': OSDeviceGPUHardwareCapabilitiesInformationToJSON(value.capabilities),
    };
}

