/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is an enum that will help provide information around what permission this person has in relate to their scope.
 * @export
 */
export const PersonAccessScopedEnum = {
    Owner: 'OWNER',
    Editor: 'EDITOR',
    Commenter: 'COMMENTER',
    Viewer: 'VIEWER'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:32 AM
 *
 * @export
 * @typedef {PersonAccessScopedEnum}
 */
export type PersonAccessScopedEnum = typeof PersonAccessScopedEnum[keyof typeof PersonAccessScopedEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:32 AM
 *
 * @export
 * @param {*} json
 * @returns {PersonAccessScopedEnum}
 */
export function PersonAccessScopedEnumFromJSON(json: any): PersonAccessScopedEnum {
    return PersonAccessScopedEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:32 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {PersonAccessScopedEnum}
 */
export function PersonAccessScopedEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonAccessScopedEnum {
    return json as PersonAccessScopedEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:32 AM
 *
 * @export
 * @param {?(PersonAccessScopedEnum | null)} [value]
 * @returns {*}
 */
export function PersonAccessScopedEnumToJSON(value?: PersonAccessScopedEnum | null): any {
    return value as any;
}

