/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * OPEN: Means that privacy is fully open
 * CLOSED: Means that privacy is fully locked down, and private
 * ANONYMOUS: Means that we are allowed to collect information but it cannot get attached to me as the user.
 * @export
 */
export const PrivacyEnum = {
    Open: 'OPEN',
    Closed: 'CLOSED',
    Anonymous: 'ANONYMOUS'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:31 AM
 *
 * @export
 * @typedef {PrivacyEnum}
 */
export type PrivacyEnum = typeof PrivacyEnum[keyof typeof PrivacyEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:31 AM
 *
 * @export
 * @param {*} json
 * @returns {PrivacyEnum}
 */
export function PrivacyEnumFromJSON(json: any): PrivacyEnum {
    return PrivacyEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:31 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {PrivacyEnum}
 */
export function PrivacyEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacyEnum {
    return json as PrivacyEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:31 AM
 *
 * @export
 * @param {?(PrivacyEnum | null)} [value]
 * @returns {*}
 */
export function PrivacyEnumToJSON(value?: PrivacyEnum | null): any {
    return value as any;
}

