/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { FlattenedPerson } from './FlattenedPerson';
import {
    FlattenedPersonFromJSON,
    FlattenedPersonFromJSONTyped,
    FlattenedPersonToJSON,
} from './FlattenedPerson';

/**
 * [DAG Safe] version of a Person Model.
 * @export
 * @interface ReferencedPerson
 */
export interface ReferencedPerson {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof ReferencedPerson
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof ReferencedPerson
     */
    id: string;
    /**
     *
     * @type {FlattenedPerson}
     * @memberof ReferencedPerson
     */
    reference?: FlattenedPerson;
}

/**
 * Check if a given object implements the ReferencedPerson interface.
 */
export function instanceOfReferencedPerson(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {*} json
 * @returns {ReferencedPerson}
 */
export function ReferencedPersonFromJSON(json: any): ReferencedPerson {
    return ReferencedPersonFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {ReferencedPerson}
 */
export function ReferencedPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferencedPerson {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': json['id'],
        'reference': !exists(json, 'reference') ? undefined : FlattenedPersonFromJSON(json['reference']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {?(ReferencedPerson | null)} [value]
 * @returns {*}
 */
export function ReferencedPersonToJSON(value?: ReferencedPerson | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
        'reference': FlattenedPersonToJSON(value.reference),
    };
}

