/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { FlattenedAnchor } from './FlattenedAnchor';
import {
    FlattenedAnchorFromJSON,
    FlattenedAnchorFromJSONTyped,
    FlattenedAnchorToJSON,
} from './FlattenedAnchor';

/**
 * This is the referenced version of a Anchor, main used for the uuid.
 * @export
 * @interface ReferencedAnchor
 */
export interface ReferencedAnchor {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof ReferencedAnchor
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof ReferencedAnchor
     */
    id: string;
    /**
     *
     * @type {FlattenedAnchor}
     * @memberof ReferencedAnchor
     */
    reference?: FlattenedAnchor;
}

/**
 * Check if a given object implements the ReferencedAnchor interface.
 */
export function instanceOfReferencedAnchor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {*} json
 * @returns {ReferencedAnchor}
 */
export function ReferencedAnchorFromJSON(json: any): ReferencedAnchor {
    return ReferencedAnchorFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {ReferencedAnchor}
 */
export function ReferencedAnchorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferencedAnchor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': json['id'],
        'reference': !exists(json, 'reference') ? undefined : FlattenedAnchorFromJSON(json['reference']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {?(ReferencedAnchor | null)} [value]
 * @returns {*}
 */
export function ReferencedAnchorToJSON(value?: ReferencedAnchor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
        'reference': FlattenedAnchorToJSON(value.reference),
    };
}

