/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { FlattenedConversationMessage } from './FlattenedConversationMessage';
import {
    FlattenedConversationMessageFromJSON,
    FlattenedConversationMessageFromJSONTyped,
    FlattenedConversationMessageToJSON,
} from './FlattenedConversationMessage';

/**
 * This is a DAG-Safe Minimal version of a ConversationMessage.
 * @export
 * @interface ReferencedConversationMessage
 */
export interface ReferencedConversationMessage {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof ReferencedConversationMessage
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof ReferencedConversationMessage
     */
    id: string;
    /**
     *
     * @type {FlattenedConversationMessage}
     * @memberof ReferencedConversationMessage
     */
    reference?: FlattenedConversationMessage;
}

/**
 * Check if a given object implements the ReferencedConversationMessage interface.
 */
export function instanceOfReferencedConversationMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {*} json
 * @returns {ReferencedConversationMessage}
 */
export function ReferencedConversationMessageFromJSON(json: any): ReferencedConversationMessage {
    return ReferencedConversationMessageFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {ReferencedConversationMessage}
 */
export function ReferencedConversationMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferencedConversationMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': json['id'],
        'reference': !exists(json, 'reference') ? undefined : FlattenedConversationMessageFromJSON(json['reference']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:29 AM
 *
 * @export
 * @param {?(ReferencedConversationMessage | null)} [value]
 * @returns {*}
 */
export function ReferencedConversationMessageToJSON(value?: ReferencedConversationMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
        'reference': FlattenedConversationMessageToJSON(value.reference),
    };
}

