/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { FlattenedUserProfile } from './FlattenedUserProfile';
import {
    FlattenedUserProfileFromJSON,
    FlattenedUserProfileFromJSONTyped,
    FlattenedUserProfileToJSON,
} from './FlattenedUserProfile';

/**
 * A object to reference a user's ID and optionally a FlattenedUserProfile Instance
 * @export
 * @interface ReferencedUser
 */
export interface ReferencedUser {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof ReferencedUser
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof ReferencedUser
     */
    id: string;
    /**
     *
     * @type {FlattenedUserProfile}
     * @memberof ReferencedUser
     */
    reference?: FlattenedUserProfile;
}

/**
 * Check if a given object implements the ReferencedUser interface.
 */
export function instanceOfReferencedUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {*} json
 * @returns {ReferencedUser}
 */
export function ReferencedUserFromJSON(json: any): ReferencedUser {
    return ReferencedUserFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {ReferencedUser}
 */
export function ReferencedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferencedUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': json['id'],
        'reference': !exists(json, 'reference') ? undefined : FlattenedUserProfileFromJSON(json['reference']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {?(ReferencedUser | null)} [value]
 * @returns {*}
 */
export function ReferencedUserToJSON(value?: ReferencedUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
        'reference': FlattenedUserProfileToJSON(value.reference),
    };
}

