/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { ReferencedAsset } from './ReferencedAsset';
import {
    ReferencedAssetFromJSON,
    ReferencedAssetFromJSONTyped,
    ReferencedAssetToJSON,
} from './ReferencedAsset';
import type { Seed } from './Seed';
import {
    SeedFromJSON,
    SeedFromJSONTyped,
    SeedToJSON,
} from './Seed';

/**
 * This is a generic model used, to wrap a seed, as well as give an identifier used to further identifiy this snippet.
 *
 * Seed is optional here because you may just want to provide the id, and not the original seed.
 *
 * id is also optional here as you may provide an id or not here.(however with specific endpoint this ID is a guarentee.)
 * @export
 * @interface RelevantQGPTSeed
 */
export interface RelevantQGPTSeed {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof RelevantQGPTSeed
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof RelevantQGPTSeed
     */
    id?: string;
    /**
     *
     * @type {Seed}
     * @memberof RelevantQGPTSeed
     */
    seed?: Seed;
    /**
     * This is an optional file path
     * @type {string}
     * @memberof RelevantQGPTSeed
     */
    path?: string;
    /**
     *
     * @type {ReferencedAsset}
     * @memberof RelevantQGPTSeed
     */
    asset?: ReferencedAsset;
}

/**
 * Check if a given object implements the RelevantQGPTSeed interface.
 */
export function instanceOfRelevantQGPTSeed(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {*} json
 * @returns {RelevantQGPTSeed}
 */
export function RelevantQGPTSeedFromJSON(json: any): RelevantQGPTSeed {
    return RelevantQGPTSeedFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {RelevantQGPTSeed}
 */
export function RelevantQGPTSeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelevantQGPTSeed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'seed': !exists(json, 'seed') ? undefined : SeedFromJSON(json['seed']),
        'path': !exists(json, 'path') ? undefined : json['path'],
        'asset': !exists(json, 'asset') ? undefined : ReferencedAssetFromJSON(json['asset']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {?(RelevantQGPTSeed | null)} [value]
 * @returns {*}
 */
export function RelevantQGPTSeedToJSON(value?: RelevantQGPTSeed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
        'seed': SeedToJSON(value.seed),
        'path': value.path,
        'asset': ReferencedAssetToJSON(value.asset),
    };
}

