/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is the specific role of a format.
 * @export
 */
export const Role = {
    Original: 'ORIGINAL',
    Additional: 'ADDITIONAL',
    Both: 'BOTH',
    Preview: 'PREVIEW'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @typedef {Role}
 */
export type Role = typeof Role[keyof typeof Role];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {*} json
 * @returns {Role}
 */
export function RoleFromJSON(json: any): Role {
    return RoleFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {Role}
 */
export function RoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Role {
    return json as Role;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:28 AM
 *
 * @export
 * @param {?(Role | null)} [value]
 * @returns {*}
 */
export function RoleToJSON(value?: Role | null): any {
    return value as any;
}

