/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { GraphicalMachineLearningProcessingEvent } from './GraphicalMachineLearningProcessingEvent';
import {
    GraphicalMachineLearningProcessingEventFromJSON,
    GraphicalMachineLearningProcessingEventFromJSONTyped,
    GraphicalMachineLearningProcessingEventToJSON,
} from './GraphicalMachineLearningProcessingEvent';
import type { TLPMachineLearningProcessingEvent } from './TLPMachineLearningProcessingEvent';
import {
    TLPMachineLearningProcessingEventFromJSON,
    TLPMachineLearningProcessingEventFromJSONTyped,
    TLPMachineLearningProcessingEventToJSON,
} from './TLPMachineLearningProcessingEvent';

/**
 *
 * @export
 * @interface SeededTrackedMachineLearningEvent
 */
export interface SeededTrackedMachineLearningEvent {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof SeededTrackedMachineLearningEvent
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {TLPMachineLearningProcessingEvent}
     * @memberof SeededTrackedMachineLearningEvent
     */
    tlp?: TLPMachineLearningProcessingEvent;
    /**
     *
     * @type {GraphicalMachineLearningProcessingEvent}
     * @memberof SeededTrackedMachineLearningEvent
     */
    graphical?: GraphicalMachineLearningProcessingEvent;
}

/**
 * Check if a given object implements the SeededTrackedMachineLearningEvent interface.
 */
export function instanceOfSeededTrackedMachineLearningEvent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:24 AM
 *
 * @export
 * @param {*} json
 * @returns {SeededTrackedMachineLearningEvent}
 */
export function SeededTrackedMachineLearningEventFromJSON(json: any): SeededTrackedMachineLearningEvent {
    return SeededTrackedMachineLearningEventFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:24 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {SeededTrackedMachineLearningEvent}
 */
export function SeededTrackedMachineLearningEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeededTrackedMachineLearningEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'tlp': !exists(json, 'tlp') ? undefined : TLPMachineLearningProcessingEventFromJSON(json['tlp']),
        'graphical': !exists(json, 'graphical') ? undefined : GraphicalMachineLearningProcessingEventFromJSON(json['graphical']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:24 AM
 *
 * @export
 * @param {?(SeededTrackedMachineLearningEvent | null)} [value]
 * @returns {*}
 */
export function SeededTrackedMachineLearningEventToJSON(value?: SeededTrackedMachineLearningEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'tlp': TLPMachineLearningProcessingEventToJSON(value.tlp),
        'graphical': GraphicalMachineLearningProcessingEventToJSON(value.graphical),
    };
}

