/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { SeededGitHubGistDistribution } from './SeededGitHubGistDistribution';
import {
    SeededGitHubGistDistributionFromJSON,
    SeededGitHubGistDistributionFromJSONTyped,
    SeededGitHubGistDistributionToJSON,
} from './SeededGitHubGistDistribution';

/**
 *
 * @export
 * @interface SeededGitHubDistribution
 */
export interface SeededGitHubDistribution {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof SeededGitHubDistribution
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {SeededGitHubGistDistribution}
     * @memberof SeededGitHubDistribution
     */
    gist?: SeededGitHubGistDistribution;
}

/**
 * Check if a given object implements the SeededGitHubDistribution interface.
 */
export function instanceOfSeededGitHubDistribution(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:25 AM
 *
 * @export
 * @param {*} json
 * @returns {SeededGitHubDistribution}
 */
export function SeededGitHubDistributionFromJSON(json: any): SeededGitHubDistribution {
    return SeededGitHubDistributionFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:25 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {SeededGitHubDistribution}
 */
export function SeededGitHubDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeededGitHubDistribution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'gist': !exists(json, 'gist') ? undefined : SeededGitHubGistDistributionFromJSON(json['gist']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:25 AM
 *
 * @export
 * @param {?(SeededGitHubDistribution | null)} [value]
 * @returns {*}
 */
export function SeededGitHubDistributionToJSON(value?: SeededGitHubDistribution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'gist': SeededGitHubGistDistributionToJSON(value.gist),
    };
}

