/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { SeededRangeConversationGroundingTemporalAssociation } from './SeededRangeConversationGroundingTemporalAssociation';
import {
    SeededRangeConversationGroundingTemporalAssociationFromJSON,
    SeededRangeConversationGroundingTemporalAssociationFromJSONTyped,
    SeededRangeConversationGroundingTemporalAssociationToJSON,
} from './SeededRangeConversationGroundingTemporalAssociation';

/**
 *
 * @export
 * @interface SeededRangeConversationGroundingAssociation
 */
export interface SeededRangeConversationGroundingAssociation {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof SeededRangeConversationGroundingAssociation
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {SeededRangeConversationGroundingTemporalAssociation}
     * @memberof SeededRangeConversationGroundingAssociation
     */
    temporal?: SeededRangeConversationGroundingTemporalAssociation;
}

/**
 * Check if a given object implements the SeededRangeConversationGroundingAssociation interface.
 */
export function instanceOfSeededRangeConversationGroundingAssociation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:25 AM
 *
 * @export
 * @param {*} json
 * @returns {SeededRangeConversationGroundingAssociation}
 */
export function SeededRangeConversationGroundingAssociationFromJSON(json: any): SeededRangeConversationGroundingAssociation {
    return SeededRangeConversationGroundingAssociationFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:25 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {SeededRangeConversationGroundingAssociation}
 */
export function SeededRangeConversationGroundingAssociationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeededRangeConversationGroundingAssociation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'temporal': !exists(json, 'temporal') ? undefined : SeededRangeConversationGroundingTemporalAssociationFromJSON(json['temporal']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:25 AM
 *
 * @export
 * @param {?(SeededRangeConversationGroundingAssociation | null)} [value]
 * @returns {*}
 */
export function SeededRangeConversationGroundingAssociationToJSON(value?: SeededRangeConversationGroundingAssociation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'temporal': SeededRangeConversationGroundingTemporalAssociationToJSON(value.temporal),
    };
}

