/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { TrackedSessionEventIdentifierDescriptionPairs } from './TrackedSessionEventIdentifierDescriptionPairs';
import {
    TrackedSessionEventIdentifierDescriptionPairsFromJSON,
    TrackedSessionEventIdentifierDescriptionPairsFromJSONTyped,
    TrackedSessionEventIdentifierDescriptionPairsToJSON,
} from './TrackedSessionEventIdentifierDescriptionPairs';

/**
 * A simple model to capture a Tracked Session to be send to the Connection API
 * @export
 * @interface SeededTrackedSessionEvent
 */
export interface SeededTrackedSessionEvent {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof SeededTrackedSessionEvent
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {TrackedSessionEventIdentifierDescriptionPairs}
     * @memberof SeededTrackedSessionEvent
     */
    identifierDescriptionPair: TrackedSessionEventIdentifierDescriptionPairs;
}

/**
 * Check if a given object implements the SeededTrackedSessionEvent interface.
 */
export function instanceOfSeededTrackedSessionEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifierDescriptionPair" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:24 AM
 *
 * @export
 * @param {*} json
 * @returns {SeededTrackedSessionEvent}
 */
export function SeededTrackedSessionEventFromJSON(json: any): SeededTrackedSessionEvent {
    return SeededTrackedSessionEventFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:24 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {SeededTrackedSessionEvent}
 */
export function SeededTrackedSessionEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeededTrackedSessionEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'identifierDescriptionPair': TrackedSessionEventIdentifierDescriptionPairsFromJSON(json['identifier_description_pair']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:24 AM
 *
 * @export
 * @param {?(SeededTrackedSessionEvent | null)} [value]
 * @returns {*}
 */
export function SeededTrackedSessionEventToJSON(value?: SeededTrackedSessionEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'identifier_description_pair': TrackedSessionEventIdentifierDescriptionPairsToJSON(value.identifierDescriptionPair),
    };
}

