/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GroupedTimestamp } from './GroupedTimestamp';
import {
    GroupedTimestampFromJSON,
    GroupedTimestampFromJSONTyped,
    GroupedTimestampToJSON,
} from './GroupedTimestamp';

/**
 * This is a specific model that will let us know at what time this user was using the application.
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * The UUID of the current Session
     * @type {string}
     * @memberof Session
     */
    id: string;
    /**
     *
     * @type {GroupedTimestamp}
     * @memberof Session
     */
    opened: GroupedTimestamp;
    /**
     *
     * @type {GroupedTimestamp}
     * @memberof Session
     */
    closed?: GroupedTimestamp;
}

/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "opened" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:23 AM
 *
 * @export
 * @param {*} json
 * @returns {Session}
 */
export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:23 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {Session}
 */
export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'opened': GroupedTimestampFromJSON(json['opened']),
        'closed': !exists(json, 'closed') ? undefined : GroupedTimestampFromJSON(json['closed']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:23 AM
 *
 * @export
 * @param {?(Session | null)} [value]
 * @returns {*}
 */
export function SessionToJSON(value?: Session | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'opened': GroupedTimestampToJSON(value.opened),
        'closed': GroupedTimestampToJSON(value.closed),
    };
}

