/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SystemExecutionCpuInformation
 */
export interface SystemExecutionCpuInformation {
    /**
     * this is the number of cpus
     * @type {number}
     * @memberof SystemExecutionCpuInformation
     */
    count: number;
    /**
     * this is the brand of cpu
     * @type {string}
     * @memberof SystemExecutionCpuInformation
     */
    brand: string;
    /**
     *
     * @type {number}
     * @memberof SystemExecutionCpuInformation
     */
    frequency: number;
}

/**
 * Check if a given object implements the SystemExecutionCpuInformation interface.
 */
export function instanceOfSystemExecutionCpuInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "brand" in value;
    isInstance = isInstance && "frequency" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:23 AM
 *
 * @export
 * @param {*} json
 * @returns {SystemExecutionCpuInformation}
 */
export function SystemExecutionCpuInformationFromJSON(json: any): SystemExecutionCpuInformation {
    return SystemExecutionCpuInformationFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:23 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {SystemExecutionCpuInformation}
 */
export function SystemExecutionCpuInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemExecutionCpuInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'count': json['count'],
        'brand': json['brand'],
        'frequency': json['frequency'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:23 AM
 *
 * @export
 * @param {?(SystemExecutionCpuInformation | null)} [value]
 * @returns {*}
 */
export function SystemExecutionCpuInformationToJSON(value?: SystemExecutionCpuInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'count': value.count,
        'brand': value.brand,
        'frequency': value.frequency,
    };
}

