/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is an enum that describes the category that that this tag is apart of.
 * @export
 */
export const TagCategoryEnum = {
    Handle: 'HANDLE',
    Email: 'EMAIL',
    Unknown: 'UNKNOWN'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @typedef {TagCategoryEnum}
 */
export type TagCategoryEnum = typeof TagCategoryEnum[keyof typeof TagCategoryEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @returns {TagCategoryEnum}
 */
export function TagCategoryEnumFromJSON(json: any): TagCategoryEnum {
    return TagCategoryEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {TagCategoryEnum}
 */
export function TagCategoryEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagCategoryEnum {
    return json as TagCategoryEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {?(TagCategoryEnum | null)} [value]
 * @returns {*}
 */
export function TagCategoryEnumToJSON(value?: TagCategoryEnum | null): any {
    return value as any;
}

