/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Classification } from './Classification';
import {
    ClassificationFromJSON,
    ClassificationFromJSONTyped,
    ClassificationToJSON,
} from './Classification';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 *
 * @export
 * @interface TLPCodeFragmentClassificationMetadata
 */
export interface TLPCodeFragmentClassificationMetadata {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof TLPCodeFragmentClassificationMetadata
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {Classification}
     * @memberof TLPCodeFragmentClassificationMetadata
     */
    context?: Classification;
    /**
     *
     * @type {Classification}
     * @memberof TLPCodeFragmentClassificationMetadata
     */
    prior?: Classification;
}

/**
 * Check if a given object implements the TLPCodeFragmentClassificationMetadata interface.
 */
export function instanceOfTLPCodeFragmentClassificationMetadata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @returns {TLPCodeFragmentClassificationMetadata}
 */
export function TLPCodeFragmentClassificationMetadataFromJSON(json: any): TLPCodeFragmentClassificationMetadata {
    return TLPCodeFragmentClassificationMetadataFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {TLPCodeFragmentClassificationMetadata}
 */
export function TLPCodeFragmentClassificationMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TLPCodeFragmentClassificationMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'context': !exists(json, 'context') ? undefined : ClassificationFromJSON(json['context']),
        'prior': !exists(json, 'prior') ? undefined : ClassificationFromJSON(json['prior']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {?(TLPCodeFragmentClassificationMetadata | null)} [value]
 * @returns {*}
 */
export function TLPCodeFragmentClassificationMetadataToJSON(value?: TLPCodeFragmentClassificationMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'context': ClassificationToJSON(value.context),
        'prior': ClassificationToJSON(value.prior),
    };
}

