/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 *
 * @export
 * @interface TLPCodeDirectoryAnalytics
 */
export interface TLPCodeDirectoryAnalytics {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof TLPCodeDirectoryAnalytics
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof TLPCodeDirectoryAnalytics
     */
    id?: string;
}

/**
 * Check if a given object implements the TLPCodeDirectoryAnalytics interface.
 */
export function instanceOfTLPCodeDirectoryAnalytics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @returns {TLPCodeDirectoryAnalytics}
 */
export function TLPCodeDirectoryAnalyticsFromJSON(json: any): TLPCodeDirectoryAnalytics {
    return TLPCodeDirectoryAnalyticsFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {TLPCodeDirectoryAnalytics}
 */
export function TLPCodeDirectoryAnalyticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TLPCodeDirectoryAnalytics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {?(TLPCodeDirectoryAnalytics | null)} [value]
 * @returns {*}
 */
export function TLPCodeDirectoryAnalyticsToJSON(value?: TLPCodeDirectoryAnalytics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
    };
}

