/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { TLPCodeFragmentReclassificationUpdates } from './TLPCodeFragmentReclassificationUpdates';
import {
    TLPCodeFragmentReclassificationUpdatesFromJSON,
    TLPCodeFragmentReclassificationUpdatesFromJSONTyped,
    TLPCodeFragmentReclassificationUpdatesToJSON,
} from './TLPCodeFragmentReclassificationUpdates';

/**
 * Model for ML big query Reclassification.
 * @export
 * @interface TLPCodeFragmentReclassification
 */
export interface TLPCodeFragmentReclassification {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof TLPCodeFragmentReclassification
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {string}
     * @memberof TLPCodeFragmentReclassification
     */
    asset: string;
    /**
     *
     * @type {string}
     * @memberof TLPCodeFragmentReclassification
     */
    model: string;
    /**
     *
     * @type {string}
     * @memberof TLPCodeFragmentReclassification
     */
    created: string;
    /**
     *
     * @type {TLPCodeFragmentReclassificationUpdates}
     * @memberof TLPCodeFragmentReclassification
     */
    updates: TLPCodeFragmentReclassificationUpdates;
    /**
     * this is the user that is reclassifying
     * @type {string}
     * @memberof TLPCodeFragmentReclassification
     */
    user: string;
    /**
     * this is the application is which this is from.
     * @type {string}
     * @memberof TLPCodeFragmentReclassification
     */
    context: string;
}

/**
 * Check if a given object implements the TLPCodeFragmentReclassification interface.
 */
export function instanceOfTLPCodeFragmentReclassification(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "asset" in value;
    isInstance = isInstance && "model" in value;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "updates" in value;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "context" in value;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @returns {TLPCodeFragmentReclassification}
 */
export function TLPCodeFragmentReclassificationFromJSON(json: any): TLPCodeFragmentReclassification {
    return TLPCodeFragmentReclassificationFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {TLPCodeFragmentReclassification}
 */
export function TLPCodeFragmentReclassificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TLPCodeFragmentReclassification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'asset': json['asset'],
        'model': json['model'],
        'created': json['created'],
        'updates': TLPCodeFragmentReclassificationUpdatesFromJSON(json['updates']),
        'user': json['user'],
        'context': json['context'],
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:22 AM
 *
 * @export
 * @param {?(TLPCodeFragmentReclassification | null)} [value]
 * @returns {*}
 */
export function TLPCodeFragmentReclassificationToJSON(value?: TLPCodeFragmentReclassification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'asset': value.asset,
        'model': value.model,
        'created': value.created,
        'updates': TLPCodeFragmentReclassificationUpdatesToJSON(value.updates),
        'user': value.user,
        'context': value.context,
    };
}

