/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Code block type like function, class, abstract
 * @export
 */
export const TLPDirectedDiscoveryFilterEnum = {
    Function: 'FUNCTION',
    Method: 'METHOD',
    Class: 'CLASS',
    Struct: 'STRUCT',
    Abstract: 'ABSTRACT',
    Comment: 'COMMENT',
    Import: 'IMPORT',
    If: 'IF',
    Loop: 'LOOP',
    Return: 'RETURN'
} as const;
/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:21 AM
 *
 * @export
 * @typedef {TLPDirectedDiscoveryFilterEnum}
 */
export type TLPDirectedDiscoveryFilterEnum = typeof TLPDirectedDiscoveryFilterEnum[keyof typeof TLPDirectedDiscoveryFilterEnum];


/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:21 AM
 *
 * @export
 * @param {*} json
 * @returns {TLPDirectedDiscoveryFilterEnum}
 */
export function TLPDirectedDiscoveryFilterEnumFromJSON(json: any): TLPDirectedDiscoveryFilterEnum {
    return TLPDirectedDiscoveryFilterEnumFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:21 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {TLPDirectedDiscoveryFilterEnum}
 */
export function TLPDirectedDiscoveryFilterEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TLPDirectedDiscoveryFilterEnum {
    return json as TLPDirectedDiscoveryFilterEnum;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:21 AM
 *
 * @export
 * @param {?(TLPDirectedDiscoveryFilterEnum | null)} [value]
 * @returns {*}
 */
export function TLPDirectedDiscoveryFilterEnumToJSON(value?: TLPDirectedDiscoveryFilterEnum | null): any {
    return value as any;
}

