/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FlattenedAssets } from './FlattenedAssets';
import {
    FlattenedAssetsFromJSON,
    FlattenedAssetsFromJSONTyped,
    FlattenedAssetsToJSON,
} from './FlattenedAssets';
import type { Space } from './Space';
import {
    SpaceFromJSON,
    SpaceFromJSONTyped,
    SpaceToJSON,
} from './Space';

/**
 * Numbers related to search results
 * @export
 * @interface TrackedAssetsEventSearchMetadataResults
 */
export interface TrackedAssetsEventSearchMetadataResults {
    /**
     * Total number of fuzzy results
     * @type {number}
     * @memberof TrackedAssetsEventSearchMetadataResults
     */
    fuzzy?: number;
    /**
     * Total number of exact results
     * @type {number}
     * @memberof TrackedAssetsEventSearchMetadataResults
     */
    exact?: number;
    /**
     *
     * @type {FlattenedAssets}
     * @memberof TrackedAssetsEventSearchMetadataResults
     */
    assets?: FlattenedAssets;
    /**
     *
     * @type {Space}
     * @memberof TrackedAssetsEventSearchMetadataResults
     */
    space?: Space;
}

/**
 * Check if a given object implements the TrackedAssetsEventSearchMetadataResults interface.
 */
export function instanceOfTrackedAssetsEventSearchMetadataResults(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:20 AM
 *
 * @export
 * @param {*} json
 * @returns {TrackedAssetsEventSearchMetadataResults}
 */
export function TrackedAssetsEventSearchMetadataResultsFromJSON(json: any): TrackedAssetsEventSearchMetadataResults {
    return TrackedAssetsEventSearchMetadataResultsFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:20 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {TrackedAssetsEventSearchMetadataResults}
 */
export function TrackedAssetsEventSearchMetadataResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackedAssetsEventSearchMetadataResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'fuzzy': !exists(json, 'fuzzy') ? undefined : json['fuzzy'],
        'exact': !exists(json, 'exact') ? undefined : json['exact'],
        'assets': !exists(json, 'assets') ? undefined : FlattenedAssetsFromJSON(json['assets']),
        'space': !exists(json, 'space') ? undefined : SpaceFromJSON(json['space']),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:20 AM
 *
 * @export
 * @param {?(TrackedAssetsEventSearchMetadataResults | null)} [value]
 * @returns {*}
 */
export function TrackedAssetsEventSearchMetadataResultsToJSON(value?: TrackedAssetsEventSearchMetadataResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'fuzzy': value.fuzzy,
        'exact': value.exact,
        'assets': FlattenedAssetsToJSON(value.assets),
        'space': SpaceToJSON(value.space),
    };
}

