/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * A base class for a collection of users and some additional meta properties.
 * @export
 * @interface Users
 */
export interface Users {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof Users
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {Array<UserProfile>}
     * @memberof Users
     */
    iterable?: Array<UserProfile>;
}

/**
 * Check if a given object implements the Users interface.
 */
export function instanceOfUsers(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:19 AM
 *
 * @export
 * @param {*} json
 * @returns {Users}
 */
export function UsersFromJSON(json: any): Users {
    return UsersFromJSONTyped(json, false);
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:19 AM
 *
 * @export
 * @param {*} json
 * @param {boolean} ignoreDiscriminator
 * @returns {Users}
 */
export function UsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Users {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': !exists(json, 'iterable') ? undefined : ((json['iterable'] as Array<any>).map(UserProfileFromJSON)),
    };
}

/**
 * ${1:Description placeholder}
 * @date 4/12/2024 - 4:03:19 AM
 *
 * @export
 * @param {?(Users | null)} [value]
 * @returns {*}
 */
export function UsersToJSON(value?: Users | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'iterable': value.iterable === undefined ? undefined : ((value.iterable as Array<any>).map(UserProfileToJSON)),
    };
}

